version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - MYSQL_USER=root
      - MYSQL_PASSWORD=  # Empty password
      - MYSQL_HOST=mysql
      - MYSQL_DB=user_service_db
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Allow empty root password
      MYSQL_DATABASE: user_service_db
    ports:
      - "3307:3306"  # Change port if needed
    networks:
      - app-network

  product-service:
    build:
      context: ./product-service  # Update this path to where your product service is located
      dockerfile: Dockerfile
    ports:
      - "3002:3002"  # Expose product-service port 3002
    environment:
      - MONGO_URI=mongodb://mongo:27017/product-db
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # Expose MongoDB port (optional)
    volumes:
      - mongo-data:/data/db  # Use named volume for persistence
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
